# Generated by Django 5.2.2 on 2025-06-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Макс. грузоподъёмность (т)')),
            ],
            options={
                'verbose_name': 'Модель самосвала',
                'verbose_name_plural': 'Модели самосвалов',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной склад', max_length=100)),
                ('volume', models.FloatField(verbose_name='Объём до разгрузки (т)')),
                ('percent_sio2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% SiO2')),
                ('percent_fe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Fe')),
                ('polygon_wkt', models.TextField(help_text='Например: POLYGON((30 10, 40 40, 20 40, 10 20, 30 10))', verbose_name='Полигон склада (WKT)')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=10, unique=True, verbose_name='Бортовой номер')),
                ('current_load', models.PositiveIntegerField(verbose_name='Текущий вес груза (т)')),
                ('percent_sio2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% SiO2')),
                ('percent_fe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Fe')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.truckmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
        migrations.CreateModel(
            name='UnloadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_input', models.CharField(help_text='Ввод формата "X Y", например "30 20"', max_length=50, verbose_name='Координаты разгрузки (X Y)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('is_inside', models.BooleanField(default=False, verbose_name='Попал в полигон')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.truck', verbose_name='Самосвал')),
            ],
            options={
                'verbose_name': 'Событие разгрузки',
                'verbose_name_plural': 'События разгрузок',
                'ordering': ['-timestamp'],
            },
        ),
    ]
